import os
import subprocess

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    RegisterEventHandler,
    TimerAction,
)
from launch.event_handlers import OnProcessExit
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    motor_bringup_share = get_package_share_directory("motor_bringup")
    robot_bringup_share = get_package_share_directory("robot_bringup")

    can_interface = LaunchConfiguration("can_interface")

    # --- Resolved paths for the CiA402 canopen config (generated by cogen_dcf at build time) ---
    bus_config    = os.path.join(motor_bringup_share, "config", "j0", "bus.yml")
    master_config = os.path.join(motor_bringup_share, "config", "j0", "master.dcf")
    master_bin    = ""

    # --- Expand the hardware URDF (resolves xacro args with real paths) ---
    hardware_urdf_xacro = os.path.join(motor_bringup_share, "config", "robot.hardware.urdf.xacro")
    robot_description_content = subprocess.check_output([
        "xacro", hardware_urdf_xacro,
        f"bus_config:={bus_config}",
        f"master_config:={master_config}",
        f"master_bin:={master_bin}",
        f"can_interface_name:=can0",
    ]).decode()

    robot_description = {"robot_description": robot_description_content}

    # 1. Bring up the CAN interface (idempotent)
    can_setup = ExecuteProcess(
        cmd=["bash", "-lc", os.path.expanduser("~/agrobot_ws/scripts/ensure_can_interface.sh")],
        output="screen",
    )

    # 2. Robot state publisher (geometry / TF, needed by MoveIt too)
    rsp_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    # 3. ros2_control manager — Cia402System for j0, GenericSystem for j1–j6
    control_node = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[
            robot_description,
            os.path.join(robot_bringup_share, "config", "ros2_controllers.yaml"),
        ],
        output="screen",
    )

    # 4. Spawn controllers once the control node is up
    spawn_jsr = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster"],
        output="screen",
    )
    spawn_arm = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["arm_controller"],
        output="screen",
    )

    # Spawn arm_controller only after joint_state_broadcaster is active
    spawn_arm_after_jsr = RegisterEventHandler(
        OnProcessExit(target_action=spawn_jsr, on_exit=[spawn_arm])
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            "can_interface",
            default_value="can0",
            description="CAN network interface name",
        ),

        can_setup,
        rsp_node,
        # Small delay so the CAN interface is confirmed up before ros2_control starts
        TimerAction(period=2.0, actions=[control_node]),
        TimerAction(period=4.0, actions=[spawn_jsr]),
        spawn_arm_after_jsr,
    ])
